config/routes.rb
Phonebook::Application.routes.draw do
   
  resources :contacts

  match '/signup', to: 'accounts#new', via: :get
  match '/signin', to: 'sessions#new', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  root to: 'static_pages#home'
 
  resources :accounts
  resources :sessions #, only: [:new, :create,:destroy]

   

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      
     </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar navbar-inverse">
			<div class="navbar-inner">
				<div class="container">
					<nav>
						<ul class="nav pull-right">
							<% if signed_in? %>
							<li><%= link_to 'Phonebook', contacts_path %></li>
							<li><%= link_to "Account Details", { :controller => "accounts", :action => "show", :id => Account.find_by_remember_token(cookies[:remember_token]).id }  %></li>
							<li><%= link_to "Sign out", signout_path, method: "delete"%> 
							<% else %>
							<li><%= link_to "Sign in", signin_path %></li>
							<% end %>
							<li><%= link_to "Help", help_path %></li>
							
						</ul>
					</nav>
				</div>
			</div>
		</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    	<![endif]-->

app/views/layouts/_shim.httml.erb
<!--[if lt IE 9]>
    	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    	<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  		
  		<%= stylesheet_link_tag    "application", media: "all" %>
  		<%= javascript_include_tag "application" %>
  		<%= csrf_meta_tags %>
  		<%= render 'layouts/shim' %>
  	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>