config/routes.rb
Phonebook::Application.routes.draw do
   
  resources :contacts

  match '/signup', to: 'accounts#new', via: :get
  match '/signin', to: 'sessions#new', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  root to: 'static_pages#home'
 
  resources :accounts
  resources :sessions #, only: [:new, :create,:destroy]

   

end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id                    :integer          not null, primary key
#  name                  :string(255)
#  email                 :string(255)
#  password              :string(255)
#  password_confirmation :string(255)
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  password_digest       :string(255)
#  remember_token        :string(255)
#

class Account < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
has_secure_password

before_save { |account| account.email =email.downcase }
before_save :create_remember_token
validates :name, presence: true, length: { maximum: 50 }
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
validates :password, presence: true, length: { minimum: 6 }
validates :password_confirmation, presence: true 
private
def create_remember_token
	self.remember_token = SecureRandom.urlsafe_base64
end
has_many :contacts, :dependent => :destroy
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
before_filter :signed_in_account, only: [:show,:edit, :update, :destroy]
before_filter :correct_account, only: [:show, :edit, :update, :destroy]
  # GET /accounts
  # GET /accounts.json
  
  # GET /accounts/1
  # GET /accounts/1.json
  def index
    #@accounts = Account.all
    redirect_to root_path
    #respond_to do |format|
      #format.html # index.html.erb
      #format.json { render json: @accounts }
    #end
  end

  def show

    @account = Account.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.json
  def new
    @account = Account.new


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
  end


  # POST /accounts
  # POST /accounts.json
  def create
  
    @account = Account.new(params[:account])

    respond_to do |format|
    
      if @account.save
       sign_in(@account)
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render json: @account, status: :created, location: @account }
    
      else
        format.html { render action: "new" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        sign_in @account
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account = Account.find_by_remember_token(cookies[:remember_token])
    @account.destroy
    respond_to do |format|
      format.html { sign_out }
      format.json { head :no_content }
      redirect_to root_url
    end
  end
  def signed_in_account
   
    redirect_to signin_url, notice: "Please sign in." unless signed_in?
  end
  def correct_account
        @user=Account.find(params[:id]).id
    
    redirect_to contacts_url, notice: "Permissions denied." unless current_user?(@user)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(account)
    gravatar_id = Digest::MD5::hexdigest(account.email.downcase) 
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: account.name, class: "gravatar")
  end
end

app/views/accounts/_form.html.erb
<div class="row">
  <div class="span6 offset3">
<%= form_for(@account) do |f| %>
  <%= render 'shared/error_messages_account' %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    
    <%= f.submit %>
  </div>
<% end %>

</div>
</div>

app/views/accounts/edit.html.erb
<h2>Editing account</h2>
<%= gravatar_for @account %>
    <a href="http://gravatar.com/emails">change</a>
<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', contacts_path %>

app/views/accounts/index.html.erb
<h1>Listing accounts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>`

<% @accounts.each do |account| %>
  <tr>
    <td><%= account.name %></td>
    <td><%= account.email %></td>
    <td><%= account.password %></td>
    <td><%= account.password_confirmation %></td>
    <td><%= link_to 'Show', account %></td>
    
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Welcome to the Sign up</title>
</head>
<h1>New Account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>
<% provide(:title, @account.name) %>
<html>
<head>
<title><%= yield(:title) %></title>
</head>

<aside class="span4">
  <section>
  <h1>
  <%= gravatar_for @account %>
  <%= @account.name %>

</h1>
<a href="http://gravatar.com/emails">change gravatar</a>
</section>
</aside>
<p>
  <b>Name:</b>
  <%= @account.name %>
</p>

<p>
  <b>Email:</b>
  <%= @account.email %>
</p>



<% if signed_in? %>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Destroy', { :controller => 'accounts', :action => 'destroy' }, method: :delete, data: { confirm: 'Are you sure?' } %> | <%= link_to 'Back', contacts_path %> 
<% else %>
<%= link_to 'Back', signin_path %>
<% end %>


<div class="row">
  
</div>
</html>